name: PR Agent Workflow

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    permissions:
      pull-requests: write
      issues: write
      checks: write
      contents: write
      deployments: write
      repository-projects: write
      statuses: write
      security-events: write
      actions: write
      packages: write
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
